# Generated by Django 3.0.6 on 2020-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='mood',
            field=models.IntegerField(choices=[(-3, 'Depressed'), (-2, 'Very sad'), (-1, 'Sad'), (0, 'Normal'), (1, 'Happy'), (2, 'Very happy'), (3, 'Ecstatic')], default=0),
        ),
        migrations.AlterField(
            model_name='mood',
            name='description',
            field=models.TextField(),
        ),
    ]
